name: update-node-version

on:
  schedule:
    - cron: '0 0 1 * *'

jobs:
  update-node:
    runs-on: ubuntu-latest

    steps:
      - uses: edp5/edp5-actions/update-node-version@v1.1.3
        with:
          token: ${{ secrets.SERVICE_TOKEN }}
